### ISSUE TITLE
Create Shoping Cart

### ISSUE THREAD

**Issue by andreasTedjas** [benetis/didactic-computing-machine#2]
Dear Benetis,

I have read your posting. it's great.
but i have the same case but i call the product from api.
the issues is when i take the product to cart, and add second product to cart it will replace the previous product.

im very happy if you can help me to solve this problem>

here is i attached the code:

`**productDetail.html**

<ion-header>
  <ion-navbar>
    <ion-title>product_detail</ion-title>
  </ion-navbar>
</ion-header>

<ion-content>
  <ion-list>
    <ion-item class="page-produk-detail " *ngFor="let takeData of inventori" >
      <ion-thumbnail>
            <img data-src="{{takeData.product__image_name}}">
      </ion-thumbnail>       
      <button>Product Name: {{takeData.product__name}}</button> 
      <h3>Price:{{takeData.product__cogs | number:'1.0-0'}}</h3>
      <h3>Stock Remain :{{takeData.quantity | number:'1.0-0'}}</h3>
     
      <button (click)="decrement()">  
        <ion-icon name="remove-circle" ></ion-icon>
      </button>
        {{curentNumber}}
      <button (click)="increment()">
        <ion-icon name="add-circle" ></ion-icon>
      </button>
      <button (click)="filterData()">Filter</button>
      <button (click)="productDetail()">Add to Cart</button>
    </ion-item>
  </ion-list>
</ion-content>

`

**productDetail.ts**
import { Component } from '@angular/core';
import { NavController, NavParams, LoadingController } from 'ionic-angular';
import { HttpClient } from '@angular/common/http';
import { Storage } from '@ionic/storage';
import { ShopCartPage } from '../shop-cart/shop-cart';

@Component({
  selector: 'page-product-detail',
  templateUrl: 'produk-detail.html',
})
export class ProdukDetailPage {
  inventori: any;
  arraySale=[];
  public curentNumber = 0;
  totalqty: number;
  numberr: any;

  constructor(public navCtrl: NavController, 
    public navParams: NavParams,
    public http: HttpClient,
    public httpClient: HttpClient,
    public loadingCtrl: LoadingController,
    private storage: Storage) {
      this.selectProduct()
  }
  increment () {
    this.curentNumber++;
  }
 
  decrement () {
    this.curentNumber--;
  }
  selectProduct(){
    let loader = this.loadingCtrl.create();
    loader.present();

    let filter = [];

    filter.push({
      field: 'location_id',
      operator: 'eq',
      value: '1',
      mode: 'and'
      });
  
      filter.push({
      field: 'product_id',
      operator: 'eq',
      value: this.navParams.get('id'),
      mode: 'and'
      });
    
   
    let param = { 
      api_token: '086090c7-2c12-4f00-9ac1-9326e8764a51',
      select: 'location__name,location_id,product_id,quantity,product__number,product__name,product__unit_name,product__unit_name2,product__unit_name3,product__unit_name4,product__unit_name5,product__unit_conversion,product__unit_conversion2,product__unit_conversion3,product__unit_conversion4,product__unit_conversion5,product__cogs,product__min_quantity,product__active,product__image_name,product__description',
      filter: JSON.stringify(filter)

    };  
  
   this.storage.get('user_api').then((userApi => {
    let apiUrl = userApi+'/inventories';
    this.httpClient.post(apiUrl, null, {params: param}).subscribe(
    getData => {
        this.inventori = getData['inventories'];//console.log(this.inventori);
    
        this.arraySale=[{
          id: this.inventori[0].product_id,
          name: this.inventori[0].product__name,
          description: this.inventori[0].product__description,
          qty: this.inventori[0].quantity,
          totalqty: this.numberr.curentNumber
        }];
        this.storage.set('sale',this.arraySale);
        console.log(this.curentNumber);

        loader.dismiss();
      }, err => {
          console.log(err);
         });
      }));
  }

  filterData(){
    this.inventori = this.inventori.filter((takeData)=>{
      return takeData.product_id > 0;
    });
  }

productDetail(){
  this.navCtrl.push(ShopCartPage);
}
  ionViewDidLoad() {
    console.log('ionViewDidLoad ProdukDetailPage');
    
  }

}

**shopcart.html**
<ion-content padding class="page-shop-cart">
    <ion-list>
      <ion-item class="page-shop-cart" *ngFor="let takeData of sale">
        <h2 text-left>ID: {{takeData.id}}</h2>
        <h2 text-left>Name: {{takeData.name}}</h2>
        <h2 text-left>Qtu: {{takeData.totalqty}}</h2>
        <h2 text-left>Description {{takeData.description}}</h2>
      </ion-item>
    </ion-list>
  </ion-content>

**shopcart.ts**
@Component({
  selector: 'page-shop-cart',
  templateUrl: 'shop-cart.html',
})
export class ShopCartPage {

  sale: any;
  constructor(public navCtrl: NavController, 
    public navParams: NavParams,
    public http: HttpClient,
    private httpClient: HttpClient,
    public loadingCtrl: LoadingController,
    private storage: Storage) {
    this.loadPeople();  
  }

loadPeople(){
  this.storage.get('sale').then((val => {
       this.sale = val;
       console.log(this.sale);
    
     }));
  ionViewDidLoad() {
    console.log('ionViewDidLoad ShopCartPage');
  }
}

thank you.
i looking for to hear from you

**Comment by benetis** [comment]
Hi, sorry for late reply. First of all - thanks for reading the blog.
However, I am not coding typescript or angular anymore - therefore can't help you debug this proble
